<?php

/**
 * classの説明(一行)：基本的にクラス名
 *
 * classの説明(複数行)：クラスに対するコメント突っ込みの類
 * HTMLに反映されたとき改行はされない
 *
 * @package magicweapon
 * @link http://www.grid-works-guild.net/MagicWeapon/ MagicWeapon
 * @access  public
 * @author  Michiaki Wuzawa <wuzawa@m-fr.net>
 **/

require_once('validator.inc');

class validator_util {

public function __construct()
{
  //
  parent::__construct();
  $this->init();
}

//
public function init()
{
}

/**
 * メソッドの説明(一行)：基本的にメソッド名
 *
 * メソッドの説明(複数行)：詳細な説明その他
 *
 * @access publicかprivateかprotectedか
 * @param 型 名前 説明
 * @return 戻り値の型 簡単な説明
 */
public function hoge($var)
{
}


//private:


} // end of class

