<?php

/**
 * data_clumpとmemcache(系)ハンドルとを紐付けるクラス
 *
 * XXX 差異のほとんどってhanlde系クラスで吸収できてるんだよねぇ…このクラスいる？
 *
 * @package magicweapon
 * @link http://www.grid-works-guild.net/MagicWeapon/ MagicWeapon
 * @access  public
 * @author  Michiaki Wuzawa <wuzawa@m-fr.net>
 * @create  $LastChangedDate$
 * @version $Revision$
 */

require_once('data_clump_kvs_adaptor_base.inc');

class data_clump_memcache_adaptor extends data_clump_kvs_adaptor_base
{


} // end of class
