<?php

/**
 * テンプレートエンジン用インタフェース
 *
 * XXX …世の中のすべてがPHP5.4以上とかになったらtraitで実装するんだ…
 *
 * @package magicweapon
 * @link http://www.grid-works-guild.net/MagicWeapon/ MagicWeapon
 * @access  public
 * @author  Michiaki Wuzawa <wuzawa@m-fr.net>
 **/

interface template_engine {

/**
 * CONV系か判定
 *
 * f_convまたはその継承クラス
 *
 * @access publicかprivateかprotectedか
 * @param 型 名前 説明
 * @return 戻り値の型 簡単な説明
 */
public function hoge($var)
{
}


//private:


} // end of class





